// <auto-generated />
using System;
using ControlUsuarios.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControlUsuarios.WebApi.Migrations
{
    [DbContext(typeof(TestSistemaDbContext))]
    [Migration("20230625163259_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.Permiso", b =>
                {
                    b.Property<Guid>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permiso");

                    b.HasData(
                        new
                        {
                            IdPermiso = new Guid("d1b59f44-ed5c-4f3b-8020-670a96190185"),
                            Descripcion = "Permisos de Administrador",
                            Name = "Full"
                        });
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.Rol", b =>
                {
                    b.Property<Guid>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            IdRol = new Guid("3b9d3bd4-77b9-431c-b669-4896868818f5"),
                            Name = "Administrador"
                        });
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.RolPermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermisoRefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolRefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermisoRefId");

                    b.HasIndex("RolRefId");

                    b.ToTable("RolPermiso");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4de80c2-0605-4a58-9258-3a3a21be6103"),
                            PermisoRefId = new Guid("d1b59f44-ed5c-4f3b-8020-670a96190185"),
                            RolRefId = new Guid("3b9d3bd4-77b9-431c-b669-4896868818f5")
                        });
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("JWT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.Usuario", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("RolRefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserName");

                    b.HasIndex("RolRefId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UserName = "Admin",
                            Clave = "w5su1y3SSQu2brHEKX5fp4uZUPfPqqPCOncMoVYHGsE=",
                            EmailAddress = "admin@intermail.com",
                            Enabled = true,
                            RolRefId = new Guid("3b9d3bd4-77b9-431c-b669-4896868818f5")
                        });
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.RolPermiso", b =>
                {
                    b.HasOne("ControlUsuarios.WebApi.Models.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlUsuarios.WebApi.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.Usuario", b =>
                {
                    b.HasOne("ControlUsuarios.WebApi.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
