// <auto-generated />
using System;
using ControlUsuarios.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControlUsuarios.WebApi.Migrations
{
    [DbContext(typeof(TestSistemaDbContext))]
    [Migration("20230625200310_migration2")]
    partial class migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.Permiso", b =>
                {
                    b.Property<Guid>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permiso");

                    b.HasData(
                        new
                        {
                            IdPermiso = new Guid("95bb4cfc-8570-42db-bc45-09cec99060ee"),
                            Descripcion = "Permisos de Cliente",
                            Name = "Cliente"
                        });
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.Rol", b =>
                {
                    b.Property<Guid>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            IdRol = new Guid("9b5f2d1c-13f9-4e9e-ab36-53506b487f37"),
                            Name = "Cliente"
                        });
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.RolPermiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermisoRefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolRefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermisoRefId");

                    b.HasIndex("RolRefId");

                    b.ToTable("RolPermiso");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0957737f-e38c-4226-89ef-65bd5158487a"),
                            PermisoRefId = new Guid("95bb4cfc-8570-42db-bc45-09cec99060ee"),
                            RolRefId = new Guid("9b5f2d1c-13f9-4e9e-ab36-53506b487f37")
                        });
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("JWT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.Usuario", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("RolRefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserName");

                    b.HasIndex("RolRefId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.RolPermiso", b =>
                {
                    b.HasOne("ControlUsuarios.WebApi.Models.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlUsuarios.WebApi.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ControlUsuarios.WebApi.Models.Usuario", b =>
                {
                    b.HasOne("ControlUsuarios.WebApi.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
